### ISSUE TITLE
Example plotConsModem.py isn't working...

### ISSUE THREAD

**Issue by tdgedenk** [veeresht/CommPy#49] opened 2019-10-29 16:21 UTC
FYI, I went ahead and tried your example.

Get this error. 

'PSKModem' object has no attribute 'plot_constellation'

I'm not the greatest at programming so I could've missed something.

**Comment by tdgedenk** [comment] 2019-10-29 17:09
![commpy](https://user-images.githubusercontent.com/52427082/67791136-d8abe000-fa6e-11e9-8a73-3f72b6b3042d.png)

**Comment by BastienTr** [comment] 2019-10-29 17:23
To be honest, I can't find of a reason why it works here but not for you... I'll try tomorrow on a friend's computer to see if I notice anything. I'll keep in touch

**Comment by tdgedenk** [comment] 2019-10-29 17:24
Yeah, me either. It is kind of weird. I remember it worked a couple months ago.

Anyway, thanks for helping! Hope to hear from you.

**Comment by BastienTr** [comment] 2019-10-30 12:21
I just tried it on two other computers that have never installed the library (a linux and a windows), it works as expected. So I'm pretty sure the problem is due to your installation. Is it possible that there is still an old version of the library in the python path?

**Comment by BastienTr** [comment] 2019-11-02 14:18
I close this as we can't find an real issue. Feel free to reopen if you can provide more details on a reproducable bug :)

**Closed by BastienTr** 2019-11-02 14:18 UTC
